# Generated by Django 5.1.5 on 2025-02-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_booking_client_alter_booking_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="read",
            field=models.CharField(
                choices=[("1", "Read"), ("2", "Unread")], default="1", max_length=30
            ),
        ),
    ]
