# Generated by Django 5.1.5 on 2025-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_worker_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="username",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
