# Generated by Django 5.1.5 on 2025-03-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_worker_category_alter_worker_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="date",
            new_name="date_booking",
        ),
    ]
