# Generated by Django 5.1.5 on 2025-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_booking_date_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="date_booking",
            field=models.DateTimeField(default="2024-03-08"),
        ),
    ]
